#!/bin/sh

#    Author:  GuoWenxue<guowenxue@gmail.com>
#      Date:  2011.04.24
#Descripion:  This shell script used to generate a ramdisk block device file

RF_MNT=mnt

if [ $# != 2 ] ; then
   echo "This shell script used to generate a ramdisk block device file"
   echo "Usage: $0 [ramdisk] [size]"
   exit;
fi

RF_NAME=$1
SIZE=$2
CMD_PREFIX=

if [ root != `whoami` ] ; then 
    echo "WARNING: Not root user, use sudo to excute this shell script commands" 
    CMD_PREFIX=sudo
fi

dd if=/dev/zero of=$RF_NAME bs=1M count=$SIZE
if [ ! -d $RF_MNT ] ; then
mkdir $RF_MNT
fi

$CMD_PREFIX mke2fs -F -v -m0 $RF_NAME

$CMD_PREFIX mount -o loop $RF_NAME $RF_MNT
$CMD_PREFIX rm -rf $RF_MNT/lost+found
$CMD_PREFIX mkdir -p $RF_MNT/{apps,bin,data,dev,info,proc,root,sbin,sys,tmp,var,etc/{,init.d,dropbear},mnt/{,usb,sdc,nfs,dev},usr/{,bin,sbin,lib,share},lib/{,modules/{,2.6.24,2.6.38}}} 

$CMD_PREFIX mknod -m755 $RF_MNT/dev/null c 1 3 
$CMD_PREFIX mknod -m755 $RF_MNT/dev/console c 5 1

$CMD_PREFIX ln -s /tmp $RF_MNT/var/lock
$CMD_PREFIX ln -s /tmp $RF_MNT/var/log
$CMD_PREFIX ln -s /tmp $RF_MNT/var/run
$CMD_PREFIX ln -s /tmp $RF_MNT/var/tmp

$CMD_PREFIX umount $RF_NAME
rm -rf $RF_MNT

